version: '{build}'
os: Visual Studio 2017
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: J44I7BBE2zLjWu8pPKX15RiOmmohBvbMu+8fjtc1kIC08J0Ek051GLm6l6YDExIa
branches:
  only:
    - master
before_build:
- choco install codecov
build_script:
- dotnet pack -c Release
test_script:
- dotnet test -c Release .\test\Nito.Guids.Tests\
- codecov -f coverage.xml
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    appveyor_repo_tag: true